# Generated by Django 5.2.1 on 2025-05-21 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop')], max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('seller_approval', models.BooleanField(default=False)),
                ('buyer_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('expertise_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expertiserequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(blank=True, choices=[(True, 'Healthy'), (False, 'Faulty')], default=None, null=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expertise_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expertiserequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('expertise_request',), name='unique_request_expert')],
            },
        ),
    ]
