# Generated by Django 5.2.1 on 2025-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiserequest',
            name='buyer_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expertiserequest',
            name='seller_approval',
            field=models.BooleanField(default=True),
        ),
    ]
